//Name: Shihab Muhtasim
//ID: 21301610
//Assignment 5
//CSE321: Operating Systems (5)

//Use -lm for compiling- used mathmatical functions
//gcc as5.c -o as5 -lm


#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <unistd.h>
#include <math.h>

int checkP2(int x);
int *dTob(int n,int l);
int bTod(int a[],int l);

int main(){
	int pgs=4; //page size
	int ms=32; //memory size
	int nof=ms/pgs; //number of frames
	int offset_bit; //find out # of bits required for offset
	int m; //find out address spaces required in main memory
	int pg_num_bit; ////find out # of bits required for page number
	int la[]={8,4,3,2,15,18,25}; //logical addresses generated by the CPU
	
	int pmt[]={3,6,8,12,2}; //page table
	
	/*
	find out corresponding physical addresses of generated logical addresses 
   	 using the formula: physical address = (frame # * page size)+offset
    	*/
	//Do your code here
    // Calculate the offset bits by taking log2 of the page size

    offset_bit = log2(pgs);

    // Calculate the page number bits
    pg_num_bit = log2(nof);

    printf("Page size: %d\n", pgs);
    printf("Memory size: %d\n", ms);
    printf("Number of frames required: %d\n", nof);
    printf("Page number bits: %d\n", pg_num_bit);
    printf("Offset bits: %d\n", offset_bit);
    printf("Number of address spaces: %d\n", pg_num_bit + offset_bit);   
	
    //print page table
    printf("Page Table\n");
    int len_p_t= sizeof(pmt)/sizeof(pmt[0]);
    for(int i=0; i<len_p_t; i++){
        printf("%d -> %d\n", i, pmt[i]);
    }

    // Calculate the physical address of each logical address
    int len_l_t= sizeof(la)/sizeof(la[0]);
    for(int i=0; i<len_l_t; i++){
        //convert the logical address to binary
        
        int *bin = dTob(la[i], pg_num_bit + offset_bit);
        printf("\n");

        //extract the bits upto pg_num_bit in another array from bin array
        int pg_num[pg_num_bit];
        for(int j=0; j<pg_num_bit; j++){
            pg_num[j] = bin[j];
        }
        
        //convert the pg_num array to decimal
        int pg_num_dec = bTod(pg_num, pg_num_bit);
        
        //extract the bits upto offset_bit in another array from bin array
        int offset[offset_bit];
        int idx=0;
        for(int j=pg_num_bit; j<pg_num_bit+offset_bit; j++){
            offset[idx] = bin[j];
            idx++;
        }
        //convert opffset to decimal
        int offset_dec = bTod(offset, offset_bit);
        
        //check if page exists
        if(pg_num_dec >= len_p_t){
            printf("%d is an invalid page number\n", pg_num_dec);     
        }
        else{
        //calculate physical address
        //get the frame number from page table
        int frame_num = pmt[pg_num_dec];
        int physical_address = (frame_num * pgs) + offset_dec;
        if (physical_address >= ms){
            printf(" %d is an Invalid physical address\n", physical_address);
        }
        else{
            printf("Corresponding physical address of logical address %d: %d\n",la[i] ,physical_address);
        }
        

        
	
    }

}
return 0;
}
// int checkP2(int x){
//     //Do your code here
//    	return ;
// }

int *dTob(int n,int l){
    //Do your code here
    static int arr[100];
    //convert decimal to binary
    for(int i=l-1; i>=0; i--){
        arr[i] = n % 2;
        n = n / 2;
        }
    
    return arr;
}

int bTod(int a[],int l){
	//convert from binary array to decimal
    int dec = 0;
    for(int i=0; i<l; i++){
        dec += a[i] * pow(2, l-i-1);
    }
    return dec;
	
}